# Generated by Django 5.2.12 on 2026-06-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='How the user paid (e.g. CCP, BaridiMob, bank transfer).', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='User-supplied payment reference / transaction number.', max_length=200),
        ),
    ]
