# Generated by Django 5.2.12 on 2026-07-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_payment_payment_method_payment_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('subscription_mode', models.CharField(choices=[('free', 'Free — everyone can redeem, no subscription needed'), ('plans', 'Plans — redemption requires an active subscription')], default='free', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
    ]
