# Generated by Django 5.2.12 on 2026-06-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Admin-controlled flag. Featured deals appear in the Featured section.'),
        ),
    ]
