# Generated by Django 5.2.12 on 2026-07-26 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0002_deal_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings (auto-computed).'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating 0.00 - 5.00 (auto-computed from DealRating).', max_digits=3),
        ),
        migrations.CreateModel(
            name='DealRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='deals_app.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_ratings',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'deal'), name='unique_user_deal_rating')],
            },
        ),
    ]
