# Generated by Django 5.2.12 on 2026-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0003_deal_ratings_count_alter_deal_rating_dealrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text="Admin-only block. Blocked deals are hidden from clients and cannot be redeemed, regardless of the business's is_active."),
        ),
    ]
