# Generated by Django 5.2.12 on 2026-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='school',
            field=models.CharField(blank=True, help_text='School or university name (optional).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='wilaya',
            field=models.CharField(default='Default Name', help_text='Algerian province / state (wilaya).', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Banned users cannot log in or access any endpoint.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for Google Maps pin (e.g. 36.737232).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for Google Maps pin (e.g. 3.086472).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
